image: Visual Studio 2017

init:
  - git config --global core.autocrlf input

build_script:
  - cmd: build.cmd 

matrix:
  fast_finish: true

environment:
    matrix:
      - USE_MSBUILD: 1
      - USE_DOTNET: 1
  
test: off

branches:
  except:
    - release